services:
  web:
    image: gabadueka/gabadueka:latest
    container_name: gabadueka-nginx
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - web-network

  php:
    image: php:8.2-fpm-alpine
    container_name: gabadueka-php
    volumes:
      - ./:/var/www/html  # In production, this should be a named volume
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
